### PR TITLE
fix(entries): Don't add css entries twice

### LINKED ISSUE #798: CSS being embedded both as <link> and <script>
## Description

`html-webpack-plugin` seems to be trying to insert a CSS chunk twice: once on a `<link>` tag and once on a `<script>` one. This doesn't happen with JS ones.

Template before:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>App</title>
        <base href="/">
        <meta http-equiv="X-UA-Compatible", content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
    </head>
    <body>
        <app>
            <div class="loading-container">
                <div class="loader">Loading...</div>
            </div>
        </app>
        <link crossorigin="anonymous" href="bundle.min.css" media="all" rel="stylesheet">
        <script async src="app.bundle.js"></script>
    </body>
</html>
```

After:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>App</title>
        <base href="/">
        <meta http-equiv="X-UA-Compatible", content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href="loader.min.css" rel="stylesheet"></head>
    <body>
        <app>
            <div class="loading-container">
                <div class="loader">Loading...</div>
            </div>
        </app>
        <link crossorigin="anonymous" href="bundle.min.css" media="all" rel="stylesheet">
        <script async src="app.bundle.js"></script>
    <script type="text/javascript" src="loader.min.css"></script><script type="text/javascript" src="newrelic.js"></script></body>
</html>
```

I know I could just manually link `loader.min.css` directly in the template, but I need it to be inlined later on (with `html-webpack-inline-source-plugin`). Here I'm not doing it just to keep matters simple.

### Config

```js
const extractText = new ExtractTextPlugin('[name]');

module.exports = {
    entry: {
        'app.bundle.js': [
            'zone.js',
            'reflect-metadata',
            path.resolve(__dirname, 'app', 'main.js'),
        ],
        'newrelic.js': [
            path.resolve(__dirname, 'app', 'assets', 'newrelic', 'newrelic.js'),
        ],
        'loader.min.css': [
            path.resolve(__dirname, 'app', 'assets', 'web', 'sass', 'loading.scss')
        ],
        'bundle.min.css': [
            path.resolve(__dirname, 'node_modules', 'photoswipe', 'dist', 'photoswipe.css'),
            path.resolve(__dirname, 'node_modules', 'photoswipe', 'dist', 'default-skin', 'default-skin.css'),
            path.resolve(__dirname, 'app', 'web', 'vendor', 'bootstrap', 'css', 'bootstrap.css'),
            path.resolve(__dirname, 'app', 'assets', 'web', 'sass', 'main.scss')
        ],
    },
    resolve: {
        extensions: ['.js', '.json'],
    },
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: '[name]',
    },
    devServer: {
        historyApiFallback: true,
        compress: true
    },
    module: {
        rules: [
            {
                test: /newrelic\.js$/,
                use: extractText.extract({
                    use: ['raw-loader'],
                }),
            },
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
                loader: 'file-loader?name=[name].[hash].[ext]',
            },
            {
                test: /\.css$/,
                use: extractText.extract({
                    use: [
                        {
                            loader: "css-loader",
                            options: {
                                minimize: true,
                                url: false
                            }
                        },
                        { loader: "resolve-url-loader" },
                    ]
                })
            },
            {
                test: /\.scss$/,
                use: extractText.extract({
                    use: [
                        {
                            loader: "css-loader",
                            options: {
                                minimize: true,
                                url: false
                            }
                        },
                        { loader: "resolve-url-loader" },
                        { loader: "sass-loader" },
                    ]
                })
            },
            {
                test: /\.pug$/,
                loaders: [
                    'html-loader',
                    {
                        loader: 'pug-html-loader',
                        options: {
                            doctype: 'html',
                        },
                    },
                ],
            },
        ],
    },
    plugins: [
        extractText,
        new CopyWebpackPlugin([
            { from: path.resolve(__dirname, 'app', 'assets', 'web', 'img'), to: path.resolve(__dirname, 'dist', 'assets', 'img')},
            { from: path.resolve(__dirname, 'app', 'assets', 'i18n'), to: path.resolve(__dirname, 'dist', 'assets', 'i18n')},
            { from: path.resolve(__dirname, 'app', 'web', 'vendor'), to: path.resolve(__dirname, 'dist', 'vendor')},
            { from: path.resolve(__dirname, 'node_modules', 'photoswipe', 'dist', 'default-skin'), to: path.resolve(__dirname, 'dist')},
        ]),
        new HtmlWebpackPlugin({
            template: 'dist/index.html',
            chunks: ['newrelic.js', 'loader.min.css'],
            inlineSource: /^.*$/,
        }),
    ],
};
```

## Environment

- Node.js v8.6.0
- macOS High Sierra
- Webpack 3.7.1
- html-webpack-plugin 2.30.1

### PR DESCRIPTION
**Pull request by jantimon**
This should fix #798 where css entries where also added as a script tag.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -437,12 +437,14 @@ class HtmlWebpackPlugin {
...
 
       // Webpack outputs an array for each chunk when using sourcemaps
-      // But we need only the entry file
+      // But we need only the initial entry file in case it is a js file
       const entry = chunkFiles[0];
-      assets.chunks[chunkName].size = chunk.size;
-      assets.chunks[chunkName].entry = entry;
-      assets.chunks[chunkName].hash = chunk.hash;
-      assets.js.push(entry);
+      if (/.css($|\?)/.test(entry)) {
```
Comment (michael-ciniawsky) [inline index.js]:
```js
if (!/\.css$/.test(entry))
```

Otherwise it still pushes the CSS entry to `assets.js` ?

Comment (jantimon) [reply index.js]: sorry totally right

**Comment by jantimon** [comment]
@michael-ciniawsky thanks for the heads up :) should work now
